### ISSUE TITLE
Actividad 3 Cuadro Comparativo_Maribel Santiago Bautista 1°BS

### ISSUE THREAD

**Issue by santiagomary1004** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-santiagomary1004#1]
[Actividad 3 Cuadro Comparativo_Maribel Santiago Bautista.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-santiagomary1004/files/9483749/Actividad.3.Cuadro.Comparativo_Maribel.Santiago.Bautista.pdf)

**Comment by AmeliReyesHernandez** [comment]
19 de 20

**Comment by josealfredo79** [comment]
BIen hecho y revisado..
